allprojects {
    repositories {
        google()
        mavenCentral()
        // Flutter plugin artifacts and Gradle Plugin Portal
        maven { url 'https://storage.googleapis.com/download.flutter.io' }
        maven { url 'https://plugins.gradle.org/m2/' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

buildscript {
    ext.kotlin_version = '1.9.0' // 或更新版本
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0' // 升級到 8.1+
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
