org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
android.enableJetifier=true

# Flutter SDK 版本配置
flutter.sdk=C:\\Users\\USER\\flutter
flutter.compileSdkVersion=34
flutter.minSdkVersion=21
flutter.targetSdkVersion=34
flutter.ndkVersion=23.1.7779620
flutter.buildMode=debug